"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import site, os, re, sys

with open(os.path.join('src', 'pytouch_cube', 'version.py'), encoding='utf-8') as f:
    version = re.search(r"^APP_VERSION = ['\"]([^'\"]*)['\"]", f.read(), re.M).group(1)

if not version:
    raise RuntimeError('Failed to parse version information')

data_files = [
    ('', ['pytouch3.png']),
]

setup_requires = ['setuptools>=61']
requires = ['PyQt6', 'django-qrcode', 'pyserial', 'packbits', 'pypng', 'appdirs', 'qasync']
kwargs = {}

if sys.argv[1:2] == ['py2app']:
    setup_requires.append('py2app')
elif sys.argv[1:2] == ['py2exe']:
    qt_plugin_root = site.getsitepackages()[1] + "\\PyQt6\\Qt\\plugins"
    kwargs = {
        "windows": [{
            "script": 'pytouch-cube/__init__.py',
            "icon_resources": [(0, "pytouch3.ico")],
            "dest_base": "pytouch3"
        }],
    }
    setup_requires.append('py2exe~=0.10.2.1')
    requires.append('wmi')
    data_files += [
        ("platforms", [ qt_plugin_root + "\\platforms\\qwindows.dll"]),
        ("iconengines", [qt_plugin_root + "\\iconengines\\qsvgicon.dll"]),
        ("platformthemes", [qt_plugin_root + "\\platformthemes\\qxdgdesktopportal.dll"]),
        ("styles", [qt_plugin_root + "\\styles\\qwindowsvistastyle.dll"])
    ]
else:
    pass


setup(
    name='pytouch-cube',
    version=version,
    author='piksel bitworks',
    data_files=data_files,
    options={
        'py2app': {
            'iconfile': 'pytouch3.icns'
        },
        'py2exe': {
            'includes': [
                'PyQt6.sip',
                'PyQt6.QtCore',
                'PyQt6.QtGui'
            ]
        }
    },
    setup_requires=setup_requires,
    install_requires=requires,
    package_dir={'': 'src'},
    packages=[
        'pytouch_cube',
        'pytouch_cube.cli', 
        'pytouch_cube.gui', 
        'pytouch_cube.printing',
        'pytouch_cube.printables',
        'barcode',
        'barcode.charsets'],
    **kwargs
)
